apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  type: NodePort
  selector:
    app: test-cluster
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 32500