apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: redis
  labels:
    pv: redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Volumes/backup/k8s/redis
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
# persistentVolumeReclaimPolicy: Recycle
#  nfs:
#    server: 192.168.8.158
#    path: /data/k8s