// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book/book.proto

package pb_book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatisBook struct {
	TotalNum             uint32       `protobuf:"varint,1,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	TodayNum             uint32       `protobuf:"varint,2,opt,name=today_num,json=todayNum,proto3" json:"today_num,omitempty"`
	Ranking              uint32       `protobuf:"varint,3,opt,name=ranking,proto3" json:"ranking,omitempty"`
	Top_50               []*TopUser50 `protobuf:"bytes,4,rep,name=top_50,json=top50,proto3" json:"top_50,omitempty"`
	FrequencyNum         uint32       `protobuf:"varint,5,opt,name=frequency_num,json=frequencyNum,proto3" json:"frequency_num,omitempty"`
	UserNum              uint32       `protobuf:"varint,6,opt,name=user_num,json=userNum,proto3" json:"user_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StatisBook) Reset()         { *m = StatisBook{} }
func (m *StatisBook) String() string { return proto.CompactTextString(m) }
func (*StatisBook) ProtoMessage()    {}
func (*StatisBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{0}
}

func (m *StatisBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisBook.Unmarshal(m, b)
}
func (m *StatisBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisBook.Marshal(b, m, deterministic)
}
func (m *StatisBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisBook.Merge(m, src)
}
func (m *StatisBook) XXX_Size() int {
	return xxx_messageInfo_StatisBook.Size(m)
}
func (m *StatisBook) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisBook.DiscardUnknown(m)
}

var xxx_messageInfo_StatisBook proto.InternalMessageInfo

func (m *StatisBook) GetTotalNum() uint32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func (m *StatisBook) GetTodayNum() uint32 {
	if m != nil {
		return m.TodayNum
	}
	return 0
}

func (m *StatisBook) GetRanking() uint32 {
	if m != nil {
		return m.Ranking
	}
	return 0
}

func (m *StatisBook) GetTop_50() []*TopUser50 {
	if m != nil {
		return m.Top_50
	}
	return nil
}

func (m *StatisBook) GetFrequencyNum() uint32 {
	if m != nil {
		return m.FrequencyNum
	}
	return 0
}

func (m *StatisBook) GetUserNum() uint32 {
	if m != nil {
		return m.UserNum
	}
	return 0
}

type StatisBookRsp struct {
	Info                 *StatisBook `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatisBookRsp) Reset()         { *m = StatisBookRsp{} }
func (m *StatisBookRsp) String() string { return proto.CompactTextString(m) }
func (*StatisBookRsp) ProtoMessage()    {}
func (*StatisBookRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{1}
}

func (m *StatisBookRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisBookRsp.Unmarshal(m, b)
}
func (m *StatisBookRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisBookRsp.Marshal(b, m, deterministic)
}
func (m *StatisBookRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisBookRsp.Merge(m, src)
}
func (m *StatisBookRsp) XXX_Size() int {
	return xxx_messageInfo_StatisBookRsp.Size(m)
}
func (m *StatisBookRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisBookRsp.DiscardUnknown(m)
}

var xxx_messageInfo_StatisBookRsp proto.InternalMessageInfo

func (m *StatisBookRsp) GetInfo() *StatisBook {
	if m != nil {
		return m.Info
	}
	return nil
}

type TopUser50 struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	TotalNum             uint32   `protobuf:"varint,2,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopUser50) Reset()         { *m = TopUser50{} }
func (m *TopUser50) String() string { return proto.CompactTextString(m) }
func (*TopUser50) ProtoMessage()    {}
func (*TopUser50) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{2}
}

func (m *TopUser50) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopUser50.Unmarshal(m, b)
}
func (m *TopUser50) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopUser50.Marshal(b, m, deterministic)
}
func (m *TopUser50) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopUser50.Merge(m, src)
}
func (m *TopUser50) XXX_Size() int {
	return xxx_messageInfo_TopUser50.Size(m)
}
func (m *TopUser50) XXX_DiscardUnknown() {
	xxx_messageInfo_TopUser50.DiscardUnknown(m)
}

var xxx_messageInfo_TopUser50 proto.InternalMessageInfo

func (m *TopUser50) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *TopUser50) GetTotalNum() uint32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func (m *TopUser50) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type BookCatesListReq struct {
	ShowLearnNum         bool     `protobuf:"varint,1,opt,name=show_learn_num,json=showLearnNum,proto3" json:"show_learn_num,omitempty"`
	TempleID             uint32   `protobuf:"varint,2,opt,name=temple_id,json=templeID,proto3" json:"temple_id,omitempty"`
	Platform             string   `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookCatesListReq) Reset()         { *m = BookCatesListReq{} }
func (m *BookCatesListReq) String() string { return proto.CompactTextString(m) }
func (*BookCatesListReq) ProtoMessage()    {}
func (*BookCatesListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{3}
}

func (m *BookCatesListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCatesListReq.Unmarshal(m, b)
}
func (m *BookCatesListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCatesListReq.Marshal(b, m, deterministic)
}
func (m *BookCatesListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCatesListReq.Merge(m, src)
}
func (m *BookCatesListReq) XXX_Size() int {
	return xxx_messageInfo_BookCatesListReq.Size(m)
}
func (m *BookCatesListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCatesListReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookCatesListReq proto.InternalMessageInfo

func (m *BookCatesListReq) GetShowLearnNum() bool {
	if m != nil {
		return m.ShowLearnNum
	}
	return false
}

func (m *BookCatesListReq) GetTempleID() uint32 {
	if m != nil {
		return m.TempleID
	}
	return 0
}

func (m *BookCatesListReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type BookCatesListRsp struct {
	Data                 []*BookCates `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BookCatesListRsp) Reset()         { *m = BookCatesListRsp{} }
func (m *BookCatesListRsp) String() string { return proto.CompactTextString(m) }
func (*BookCatesListRsp) ProtoMessage()    {}
func (*BookCatesListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{4}
}

func (m *BookCatesListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCatesListRsp.Unmarshal(m, b)
}
func (m *BookCatesListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCatesListRsp.Marshal(b, m, deterministic)
}
func (m *BookCatesListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCatesListRsp.Merge(m, src)
}
func (m *BookCatesListRsp) XXX_Size() int {
	return xxx_messageInfo_BookCatesListRsp.Size(m)
}
func (m *BookCatesListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCatesListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookCatesListRsp proto.InternalMessageInfo

func (m *BookCatesListRsp) GetData() []*BookCates {
	if m != nil {
		return m.Data
	}
	return nil
}

//分类结构体
type BookCates struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SubCate              uint32   `protobuf:"varint,3,opt,name=sub_cate,json=subCate,proto3" json:"sub_cate,omitempty"`
	Sort                 uint32   `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	LearnNum             uint32   `protobuf:"varint,5,opt,name=learn_num,json=learnNum,proto3" json:"learn_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookCates) Reset()         { *m = BookCates{} }
func (m *BookCates) String() string { return proto.CompactTextString(m) }
func (*BookCates) ProtoMessage()    {}
func (*BookCates) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{5}
}

func (m *BookCates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCates.Unmarshal(m, b)
}
func (m *BookCates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCates.Marshal(b, m, deterministic)
}
func (m *BookCates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCates.Merge(m, src)
}
func (m *BookCates) XXX_Size() int {
	return xxx_messageInfo_BookCates.Size(m)
}
func (m *BookCates) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCates.DiscardUnknown(m)
}

var xxx_messageInfo_BookCates proto.InternalMessageInfo

func (m *BookCates) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BookCates) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BookCates) GetSubCate() uint32 {
	if m != nil {
		return m.SubCate
	}
	return 0
}

func (m *BookCates) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *BookCates) GetLearnNum() uint32 {
	if m != nil {
		return m.LearnNum
	}
	return 0
}

//子分类结构体
type BookSubCates struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CateID               uint32   `protobuf:"varint,3,opt,name=cate_id,json=cateID,proto3" json:"cate_id,omitempty"`
	TempleID             uint32   `protobuf:"varint,4,opt,name=temple_id,json=templeID,proto3" json:"temple_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BType                uint32   `protobuf:"varint,6,opt,name=b_type,json=bType,proto3" json:"b_type,omitempty"`
	Limit                uint32   `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	Book                 []*Book  `protobuf:"bytes,9,rep,name=book,proto3" json:"book,omitempty"`
	Platform             string   `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookSubCates) Reset()         { *m = BookSubCates{} }
func (m *BookSubCates) String() string { return proto.CompactTextString(m) }
func (*BookSubCates) ProtoMessage()    {}
func (*BookSubCates) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{6}
}

func (m *BookSubCates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookSubCates.Unmarshal(m, b)
}
func (m *BookSubCates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookSubCates.Marshal(b, m, deterministic)
}
func (m *BookSubCates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookSubCates.Merge(m, src)
}
func (m *BookSubCates) XXX_Size() int {
	return xxx_messageInfo_BookSubCates.Size(m)
}
func (m *BookSubCates) XXX_DiscardUnknown() {
	xxx_messageInfo_BookSubCates.DiscardUnknown(m)
}

var xxx_messageInfo_BookSubCates proto.InternalMessageInfo

func (m *BookSubCates) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BookSubCates) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BookSubCates) GetCateID() uint32 {
	if m != nil {
		return m.CateID
	}
	return 0
}

func (m *BookSubCates) GetTempleID() uint32 {
	if m != nil {
		return m.TempleID
	}
	return 0
}

func (m *BookSubCates) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *BookSubCates) GetBType() uint32 {
	if m != nil {
		return m.BType
	}
	return 0
}

func (m *BookSubCates) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *BookSubCates) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BookSubCates) GetBook() []*Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *BookSubCates) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type BookSubCatesListReq struct {
	BookSubCates         *BookSubCates `protobuf:"bytes,1,opt,name=BookSubCates,proto3" json:"BookSubCates,omitempty"`
	IDs                  []uint32      `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BookSubCatesListReq) Reset()         { *m = BookSubCatesListReq{} }
func (m *BookSubCatesListReq) String() string { return proto.CompactTextString(m) }
func (*BookSubCatesListReq) ProtoMessage()    {}
func (*BookSubCatesListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{7}
}

func (m *BookSubCatesListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookSubCatesListReq.Unmarshal(m, b)
}
func (m *BookSubCatesListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookSubCatesListReq.Marshal(b, m, deterministic)
}
func (m *BookSubCatesListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookSubCatesListReq.Merge(m, src)
}
func (m *BookSubCatesListReq) XXX_Size() int {
	return xxx_messageInfo_BookSubCatesListReq.Size(m)
}
func (m *BookSubCatesListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookSubCatesListReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookSubCatesListReq proto.InternalMessageInfo

func (m *BookSubCatesListReq) GetBookSubCates() *BookSubCates {
	if m != nil {
		return m.BookSubCates
	}
	return nil
}

func (m *BookSubCatesListReq) GetIDs() []uint32 {
	if m != nil {
		return m.IDs
	}
	return nil
}

type BookSubCatesListRsp struct {
	Total                int64           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*BookSubCates `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BookSubCatesListRsp) Reset()         { *m = BookSubCatesListRsp{} }
func (m *BookSubCatesListRsp) String() string { return proto.CompactTextString(m) }
func (*BookSubCatesListRsp) ProtoMessage()    {}
func (*BookSubCatesListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{8}
}

func (m *BookSubCatesListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookSubCatesListRsp.Unmarshal(m, b)
}
func (m *BookSubCatesListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookSubCatesListRsp.Marshal(b, m, deterministic)
}
func (m *BookSubCatesListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookSubCatesListRsp.Merge(m, src)
}
func (m *BookSubCatesListRsp) XXX_Size() int {
	return xxx_messageInfo_BookSubCatesListRsp.Size(m)
}
func (m *BookSubCatesListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookSubCatesListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookSubCatesListRsp proto.InternalMessageInfo

func (m *BookSubCatesListRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BookSubCatesListRsp) GetData() []*BookSubCates {
	if m != nil {
		return m.Data
	}
	return nil
}

//公用返回响应体
type CommonRsp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ID                   uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRsp) Reset()         { *m = CommonRsp{} }
func (m *CommonRsp) String() string { return proto.CompactTextString(m) }
func (*CommonRsp) ProtoMessage()    {}
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{9}
}

func (m *CommonRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRsp.Unmarshal(m, b)
}
func (m *CommonRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRsp.Marshal(b, m, deterministic)
}
func (m *CommonRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRsp.Merge(m, src)
}
func (m *CommonRsp) XXX_Size() int {
	return xxx_messageInfo_CommonRsp.Size(m)
}
func (m *CommonRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRsp proto.InternalMessageInfo

func (m *CommonRsp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CommonRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CommonRsp) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

//学佛列表响应
type BookListRsp struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Book  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookListRsp) Reset()         { *m = BookListRsp{} }
func (m *BookListRsp) String() string { return proto.CompactTextString(m) }
func (*BookListRsp) ProtoMessage()    {}
func (*BookListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{10}
}

func (m *BookListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookListRsp.Unmarshal(m, b)
}
func (m *BookListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookListRsp.Marshal(b, m, deterministic)
}
func (m *BookListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookListRsp.Merge(m, src)
}
func (m *BookListRsp) XXX_Size() int {
	return xxx_messageInfo_BookListRsp.Size(m)
}
func (m *BookListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookListRsp proto.InternalMessageInfo

func (m *BookListRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BookListRsp) GetData() []*Book {
	if m != nil {
		return m.Data
	}
	return nil
}

//学佛内容结构体
type Book struct {
	ID                   uint32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CateID               uint32           `protobuf:"varint,3,opt,name=cate_id,json=cateID,proto3" json:"cate_id,omitempty"`
	SubCateID            uint32           `protobuf:"varint,4,opt,name=sub_cate_id,json=subCateID,proto3" json:"sub_cate_id,omitempty"`
	Storage              uint32           `protobuf:"varint,5,opt,name=storage,proto3" json:"storage,omitempty"`
	Video                string           `protobuf:"bytes,6,opt,name=video,proto3" json:"video,omitempty"`
	Audio                uint32           `protobuf:"varint,7,opt,name=audio,proto3" json:"audio,omitempty"`
	BookFile             uint32           `protobuf:"varint,8,opt,name=book_file,json=bookFile,proto3" json:"book_file,omitempty"`
	Subject              string           `protobuf:"bytes,9,opt,name=subject,proto3" json:"subject,omitempty"`
	Content              string           `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	IsPulish             int32            `protobuf:"varint,11,opt,name=is_pulish,json=isPulish,proto3" json:"is_pulish,omitempty"`
	Hits                 uint32           `protobuf:"varint,12,opt,name=hits,proto3" json:"hits,omitempty"`
	TempleID             uint32           `protobuf:"varint,13,opt,name=temple_id,json=templeID,proto3" json:"temple_id,omitempty"`
	UserID               uint32           `protobuf:"varint,14,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	Author               string           `protobuf:"bytes,15,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt            string           `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string           `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Limit                uint32           `protobuf:"varint,18,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32           `protobuf:"varint,19,opt,name=offset,proto3" json:"offset,omitempty"`
	HasCollect           bool             `protobuf:"varint,20,opt,name=has_collect,json=hasCollect,proto3" json:"has_collect,omitempty"`
	Collect              *BookCollections `protobuf:"bytes,21,opt,name=collect,proto3" json:"collect,omitempty"`
	Platform             string           `protobuf:"bytes,22,opt,name=platform,proto3" json:"platform,omitempty"`
	Flag                 uint32           `protobuf:"varint,23,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{11}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetCateID() uint32 {
	if m != nil {
		return m.CateID
	}
	return 0
}

func (m *Book) GetSubCateID() uint32 {
	if m != nil {
		return m.SubCateID
	}
	return 0
}

func (m *Book) GetStorage() uint32 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *Book) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

func (m *Book) GetAudio() uint32 {
	if m != nil {
		return m.Audio
	}
	return 0
}

func (m *Book) GetBookFile() uint32 {
	if m != nil {
		return m.BookFile
	}
	return 0
}

func (m *Book) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Book) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Book) GetIsPulish() int32 {
	if m != nil {
		return m.IsPulish
	}
	return 0
}

func (m *Book) GetHits() uint32 {
	if m != nil {
		return m.Hits
	}
	return 0
}

func (m *Book) GetTempleID() uint32 {
	if m != nil {
		return m.TempleID
	}
	return 0
}

func (m *Book) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Book) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Book) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Book) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Book) GetHasCollect() bool {
	if m != nil {
		return m.HasCollect
	}
	return false
}

func (m *Book) GetCollect() *BookCollections {
	if m != nil {
		return m.Collect
	}
	return nil
}

func (m *Book) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Book) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type Users struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{12}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Users) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Users) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

//经书收藏
type BookCollections struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	TempleID             uint32   `protobuf:"varint,2,opt,name=temple_id,json=templeID,proto3" json:"temple_id,omitempty"`
	BookID               uint32   `protobuf:"varint,3,opt,name=book_id,json=bookID,proto3" json:"book_id,omitempty"`
	Frequency            uint32   `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	CompletionRatio      uint32   `protobuf:"varint,5,opt,name=completion_ratio,json=completionRatio,proto3" json:"completion_ratio,omitempty"`
	TotalNum             uint32   `protobuf:"varint,6,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookCollections) Reset()         { *m = BookCollections{} }
func (m *BookCollections) String() string { return proto.CompactTextString(m) }
func (*BookCollections) ProtoMessage()    {}
func (*BookCollections) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{13}
}

func (m *BookCollections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCollections.Unmarshal(m, b)
}
func (m *BookCollections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCollections.Marshal(b, m, deterministic)
}
func (m *BookCollections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCollections.Merge(m, src)
}
func (m *BookCollections) XXX_Size() int {
	return xxx_messageInfo_BookCollections.Size(m)
}
func (m *BookCollections) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCollections.DiscardUnknown(m)
}

var xxx_messageInfo_BookCollections proto.InternalMessageInfo

func (m *BookCollections) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BookCollections) GetTempleID() uint32 {
	if m != nil {
		return m.TempleID
	}
	return 0
}

func (m *BookCollections) GetBookID() uint32 {
	if m != nil {
		return m.BookID
	}
	return 0
}

func (m *BookCollections) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *BookCollections) GetCompletionRatio() uint32 {
	if m != nil {
		return m.CompletionRatio
	}
	return 0
}

func (m *BookCollections) GetTotalNum() uint32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func (m *BookCollections) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BookCollections) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

//抄经记录
type BookRecord struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookID               uint32   `protobuf:"varint,2,opt,name=book_id,json=bookID,proto3" json:"book_id,omitempty"`
	UserID               uint32   `protobuf:"varint,3,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	TempleID             uint32   `protobuf:"varint,4,opt,name=temple_id,json=templeID,proto3" json:"temple_id,omitempty"`
	TotalNum             uint32   `protobuf:"varint,5,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BookName             string   `protobuf:"bytes,7,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	Page                 *Page    `protobuf:"bytes,8,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRecord) Reset()         { *m = BookRecord{} }
func (m *BookRecord) String() string { return proto.CompactTextString(m) }
func (*BookRecord) ProtoMessage()    {}
func (*BookRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{14}
}

func (m *BookRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRecord.Unmarshal(m, b)
}
func (m *BookRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRecord.Marshal(b, m, deterministic)
}
func (m *BookRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRecord.Merge(m, src)
}
func (m *BookRecord) XXX_Size() int {
	return xxx_messageInfo_BookRecord.Size(m)
}
func (m *BookRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BookRecord proto.InternalMessageInfo

func (m *BookRecord) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BookRecord) GetBookID() uint32 {
	if m != nil {
		return m.BookID
	}
	return 0
}

func (m *BookRecord) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BookRecord) GetTempleID() uint32 {
	if m != nil {
		return m.TempleID
	}
	return 0
}

func (m *BookRecord) GetTotalNum() uint32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func (m *BookRecord) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *BookRecord) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *BookRecord) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type BookRecordListRsp struct {
	Total                int64         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*BookRecord `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BookRecordListRsp) Reset()         { *m = BookRecordListRsp{} }
func (m *BookRecordListRsp) String() string { return proto.CompactTextString(m) }
func (*BookRecordListRsp) ProtoMessage()    {}
func (*BookRecordListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{15}
}

func (m *BookRecordListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRecordListRsp.Unmarshal(m, b)
}
func (m *BookRecordListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRecordListRsp.Marshal(b, m, deterministic)
}
func (m *BookRecordListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRecordListRsp.Merge(m, src)
}
func (m *BookRecordListRsp) XXX_Size() int {
	return xxx_messageInfo_BookRecordListRsp.Size(m)
}
func (m *BookRecordListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRecordListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookRecordListRsp proto.InternalMessageInfo

func (m *BookRecordListRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BookRecordListRsp) GetData() []*BookRecord {
	if m != nil {
		return m.Data
	}
	return nil
}

type Page struct {
	Limit                uint32   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{16}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Page) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type BookInfoRsp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Info                 *Book    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookInfoRsp) Reset()         { *m = BookInfoRsp{} }
func (m *BookInfoRsp) String() string { return proto.CompactTextString(m) }
func (*BookInfoRsp) ProtoMessage()    {}
func (*BookInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{17}
}

func (m *BookInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInfoRsp.Unmarshal(m, b)
}
func (m *BookInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInfoRsp.Marshal(b, m, deterministic)
}
func (m *BookInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInfoRsp.Merge(m, src)
}
func (m *BookInfoRsp) XXX_Size() int {
	return xxx_messageInfo_BookInfoRsp.Size(m)
}
func (m *BookInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookInfoRsp proto.InternalMessageInfo

func (m *BookInfoRsp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *BookInfoRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BookInfoRsp) GetInfo() *Book {
	if m != nil {
		return m.Info
	}
	return nil
}

type BookRecordExt struct {
	BookRecord           *BookRecord `protobuf:"bytes,1,opt,name=book_record,json=bookRecord,proto3" json:"book_record,omitempty"`
	User                 *Users      `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BookRecordExt) Reset()         { *m = BookRecordExt{} }
func (m *BookRecordExt) String() string { return proto.CompactTextString(m) }
func (*BookRecordExt) ProtoMessage()    {}
func (*BookRecordExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{18}
}

func (m *BookRecordExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRecordExt.Unmarshal(m, b)
}
func (m *BookRecordExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRecordExt.Marshal(b, m, deterministic)
}
func (m *BookRecordExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRecordExt.Merge(m, src)
}
func (m *BookRecordExt) XXX_Size() int {
	return xxx_messageInfo_BookRecordExt.Size(m)
}
func (m *BookRecordExt) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRecordExt.DiscardUnknown(m)
}

var xxx_messageInfo_BookRecordExt proto.InternalMessageInfo

func (m *BookRecordExt) GetBookRecord() *BookRecord {
	if m != nil {
		return m.BookRecord
	}
	return nil
}

func (m *BookRecordExt) GetUser() *Users {
	if m != nil {
		return m.User
	}
	return nil
}

type BookRecordInfoRsp struct {
	Info                 *BookRecordExt `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BookRecordInfoRsp) Reset()         { *m = BookRecordInfoRsp{} }
func (m *BookRecordInfoRsp) String() string { return proto.CompactTextString(m) }
func (*BookRecordInfoRsp) ProtoMessage()    {}
func (*BookRecordInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{19}
}

func (m *BookRecordInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRecordInfoRsp.Unmarshal(m, b)
}
func (m *BookRecordInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRecordInfoRsp.Marshal(b, m, deterministic)
}
func (m *BookRecordInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRecordInfoRsp.Merge(m, src)
}
func (m *BookRecordInfoRsp) XXX_Size() int {
	return xxx_messageInfo_BookRecordInfoRsp.Size(m)
}
func (m *BookRecordInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRecordInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookRecordInfoRsp proto.InternalMessageInfo

func (m *BookRecordInfoRsp) GetInfo() *BookRecordExt {
	if m != nil {
		return m.Info
	}
	return nil
}

//抄经完成记录
type BookCompleteRecord struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookID               uint32   `protobuf:"varint,2,opt,name=book_id,json=bookID,proto3" json:"book_id,omitempty"`
	UserID               uint32   `protobuf:"varint,3,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	TempleID             uint32   `protobuf:"varint,4,opt,name=temple_id,json=templeID,proto3" json:"temple_id,omitempty"`
	Image                uint32   `protobuf:"varint,5,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BookName             string   `protobuf:"bytes,7,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookCompleteRecord) Reset()         { *m = BookCompleteRecord{} }
func (m *BookCompleteRecord) String() string { return proto.CompactTextString(m) }
func (*BookCompleteRecord) ProtoMessage()    {}
func (*BookCompleteRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{20}
}

func (m *BookCompleteRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCompleteRecord.Unmarshal(m, b)
}
func (m *BookCompleteRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCompleteRecord.Marshal(b, m, deterministic)
}
func (m *BookCompleteRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCompleteRecord.Merge(m, src)
}
func (m *BookCompleteRecord) XXX_Size() int {
	return xxx_messageInfo_BookCompleteRecord.Size(m)
}
func (m *BookCompleteRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCompleteRecord.DiscardUnknown(m)
}

var xxx_messageInfo_BookCompleteRecord proto.InternalMessageInfo

func (m *BookCompleteRecord) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *BookCompleteRecord) GetBookID() uint32 {
	if m != nil {
		return m.BookID
	}
	return 0
}

func (m *BookCompleteRecord) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BookCompleteRecord) GetTempleID() uint32 {
	if m != nil {
		return m.TempleID
	}
	return 0
}

func (m *BookCompleteRecord) GetImage() uint32 {
	if m != nil {
		return m.Image
	}
	return 0
}

func (m *BookCompleteRecord) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *BookCompleteRecord) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

type BookCompleteRecordListReq struct {
	BookCompleteRecord   *BookCompleteRecord `protobuf:"bytes,1,opt,name=BookCompleteRecord,proto3" json:"BookCompleteRecord,omitempty"`
	Page                 *Page               `protobuf:"bytes,2,opt,name=Page,proto3" json:"Page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BookCompleteRecordListReq) Reset()         { *m = BookCompleteRecordListReq{} }
func (m *BookCompleteRecordListReq) String() string { return proto.CompactTextString(m) }
func (*BookCompleteRecordListReq) ProtoMessage()    {}
func (*BookCompleteRecordListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{21}
}

func (m *BookCompleteRecordListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCompleteRecordListReq.Unmarshal(m, b)
}
func (m *BookCompleteRecordListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCompleteRecordListReq.Marshal(b, m, deterministic)
}
func (m *BookCompleteRecordListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCompleteRecordListReq.Merge(m, src)
}
func (m *BookCompleteRecordListReq) XXX_Size() int {
	return xxx_messageInfo_BookCompleteRecordListReq.Size(m)
}
func (m *BookCompleteRecordListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCompleteRecordListReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookCompleteRecordListReq proto.InternalMessageInfo

func (m *BookCompleteRecordListReq) GetBookCompleteRecord() *BookCompleteRecord {
	if m != nil {
		return m.BookCompleteRecord
	}
	return nil
}

func (m *BookCompleteRecordListReq) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type BookCompleteRecordExt struct {
	BookCompleteRecord   *BookCompleteRecord `protobuf:"bytes,1,opt,name=BookCompleteRecord,proto3" json:"BookCompleteRecord,omitempty"`
	Users                *Users              `protobuf:"bytes,2,opt,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BookCompleteRecordExt) Reset()         { *m = BookCompleteRecordExt{} }
func (m *BookCompleteRecordExt) String() string { return proto.CompactTextString(m) }
func (*BookCompleteRecordExt) ProtoMessage()    {}
func (*BookCompleteRecordExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{22}
}

func (m *BookCompleteRecordExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCompleteRecordExt.Unmarshal(m, b)
}
func (m *BookCompleteRecordExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCompleteRecordExt.Marshal(b, m, deterministic)
}
func (m *BookCompleteRecordExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCompleteRecordExt.Merge(m, src)
}
func (m *BookCompleteRecordExt) XXX_Size() int {
	return xxx_messageInfo_BookCompleteRecordExt.Size(m)
}
func (m *BookCompleteRecordExt) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCompleteRecordExt.DiscardUnknown(m)
}

var xxx_messageInfo_BookCompleteRecordExt proto.InternalMessageInfo

func (m *BookCompleteRecordExt) GetBookCompleteRecord() *BookCompleteRecord {
	if m != nil {
		return m.BookCompleteRecord
	}
	return nil
}

func (m *BookCompleteRecordExt) GetUsers() *Users {
	if m != nil {
		return m.Users
	}
	return nil
}

type BookCompleteRecordListRsp struct {
	Total                int64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*BookCompleteRecord `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BookCompleteRecordListRsp) Reset()         { *m = BookCompleteRecordListRsp{} }
func (m *BookCompleteRecordListRsp) String() string { return proto.CompactTextString(m) }
func (*BookCompleteRecordListRsp) ProtoMessage()    {}
func (*BookCompleteRecordListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{23}
}

func (m *BookCompleteRecordListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCompleteRecordListRsp.Unmarshal(m, b)
}
func (m *BookCompleteRecordListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCompleteRecordListRsp.Marshal(b, m, deterministic)
}
func (m *BookCompleteRecordListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCompleteRecordListRsp.Merge(m, src)
}
func (m *BookCompleteRecordListRsp) XXX_Size() int {
	return xxx_messageInfo_BookCompleteRecordListRsp.Size(m)
}
func (m *BookCompleteRecordListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCompleteRecordListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookCompleteRecordListRsp proto.InternalMessageInfo

func (m *BookCompleteRecordListRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BookCompleteRecordListRsp) GetData() []*BookCompleteRecord {
	if m != nil {
		return m.Data
	}
	return nil
}

type BookCompleteRecordInfoRsp struct {
	Info                 *BookCompleteRecordExt `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BookCompleteRecordInfoRsp) Reset()         { *m = BookCompleteRecordInfoRsp{} }
func (m *BookCompleteRecordInfoRsp) String() string { return proto.CompactTextString(m) }
func (*BookCompleteRecordInfoRsp) ProtoMessage()    {}
func (*BookCompleteRecordInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{24}
}

func (m *BookCompleteRecordInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCompleteRecordInfoRsp.Unmarshal(m, b)
}
func (m *BookCompleteRecordInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCompleteRecordInfoRsp.Marshal(b, m, deterministic)
}
func (m *BookCompleteRecordInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCompleteRecordInfoRsp.Merge(m, src)
}
func (m *BookCompleteRecordInfoRsp) XXX_Size() int {
	return xxx_messageInfo_BookCompleteRecordInfoRsp.Size(m)
}
func (m *BookCompleteRecordInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCompleteRecordInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BookCompleteRecordInfoRsp proto.InternalMessageInfo

func (m *BookCompleteRecordInfoRsp) GetInfo() *BookCompleteRecordExt {
	if m != nil {
		return m.Info
	}
	return nil
}

type BookSyncReq struct {
	TemlpeIDs            []uint32 `protobuf:"varint,1,rep,packed,name=temlpe_ids,json=temlpeIDs,proto3" json:"temlpe_ids,omitempty"`
	SourceTempleID       uint32   `protobuf:"varint,2,opt,name=source_temple_id,json=sourceTempleID,proto3" json:"source_temple_id,omitempty"`
	IsSyncPublic         uint32   `protobuf:"varint,3,opt,name=is_sync_public,json=isSyncPublic,proto3" json:"is_sync_public,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookSyncReq) Reset()         { *m = BookSyncReq{} }
func (m *BookSyncReq) String() string { return proto.CompactTextString(m) }
func (*BookSyncReq) ProtoMessage()    {}
func (*BookSyncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee9082fb44230b1b, []int{25}
}

func (m *BookSyncReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookSyncReq.Unmarshal(m, b)
}
func (m *BookSyncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookSyncReq.Marshal(b, m, deterministic)
}
func (m *BookSyncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookSyncReq.Merge(m, src)
}
func (m *BookSyncReq) XXX_Size() int {
	return xxx_messageInfo_BookSyncReq.Size(m)
}
func (m *BookSyncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BookSyncReq.DiscardUnknown(m)
}

var xxx_messageInfo_BookSyncReq proto.InternalMessageInfo

func (m *BookSyncReq) GetTemlpeIDs() []uint32 {
	if m != nil {
		return m.TemlpeIDs
	}
	return nil
}

func (m *BookSyncReq) GetSourceTempleID() uint32 {
	if m != nil {
		return m.SourceTempleID
	}
	return 0
}

func (m *BookSyncReq) GetIsSyncPublic() uint32 {
	if m != nil {
		return m.IsSyncPublic
	}
	return 0
}

func init() {
	proto.RegisterType((*StatisBook)(nil), "pb.book.StatisBook")
	proto.RegisterType((*StatisBookRsp)(nil), "pb.book.StatisBookRsp")
	proto.RegisterType((*TopUser50)(nil), "pb.book.TopUser50")
	proto.RegisterType((*BookCatesListReq)(nil), "pb.book.BookCatesListReq")
	proto.RegisterType((*BookCatesListRsp)(nil), "pb.book.BookCatesListRsp")
	proto.RegisterType((*BookCates)(nil), "pb.book.BookCates")
	proto.RegisterType((*BookSubCates)(nil), "pb.book.BookSubCates")
	proto.RegisterType((*BookSubCatesListReq)(nil), "pb.book.BookSubCatesListReq")
	proto.RegisterType((*BookSubCatesListRsp)(nil), "pb.book.BookSubCatesListRsp")
	proto.RegisterType((*CommonRsp)(nil), "pb.book.CommonRsp")
	proto.RegisterType((*BookListRsp)(nil), "pb.book.BookListRsp")
	proto.RegisterType((*Book)(nil), "pb.book.Book")
	proto.RegisterType((*Users)(nil), "pb.book.Users")
	proto.RegisterType((*BookCollections)(nil), "pb.book.BookCollections")
	proto.RegisterType((*BookRecord)(nil), "pb.book.BookRecord")
	proto.RegisterType((*BookRecordListRsp)(nil), "pb.book.BookRecordListRsp")
	proto.RegisterType((*Page)(nil), "pb.book.Page")
	proto.RegisterType((*BookInfoRsp)(nil), "pb.book.BookInfoRsp")
	proto.RegisterType((*BookRecordExt)(nil), "pb.book.BookRecordExt")
	proto.RegisterType((*BookRecordInfoRsp)(nil), "pb.book.BookRecordInfoRsp")
	proto.RegisterType((*BookCompleteRecord)(nil), "pb.book.BookCompleteRecord")
	proto.RegisterType((*BookCompleteRecordListReq)(nil), "pb.book.BookCompleteRecordListReq")
	proto.RegisterType((*BookCompleteRecordExt)(nil), "pb.book.BookCompleteRecordExt")
	proto.RegisterType((*BookCompleteRecordListRsp)(nil), "pb.book.BookCompleteRecordListRsp")
	proto.RegisterType((*BookCompleteRecordInfoRsp)(nil), "pb.book.BookCompleteRecordInfoRsp")
	proto.RegisterType((*BookSyncReq)(nil), "pb.book.BookSyncReq")
}

func init() { proto.RegisterFile("book/book.proto", fileDescriptor_ee9082fb44230b1b) }

var fileDescriptor_ee9082fb44230b1b = []byte{
	// 1362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x6d, 0x6f, 0x1b, 0xc5,
	0x13, 0xaf, 0x1f, 0x63, 0x8f, 0x63, 0x27, 0xdd, 0x3c, 0x5d, 0xdb, 0x7f, 0xfb, 0x4f, 0x8e, 0x8a,
	0xa6, 0xbc, 0x48, 0x43, 0x68, 0x25, 0x40, 0x42, 0xa8, 0x94, 0x56, 0x8a, 0xa8, 0x4a, 0x74, 0x69,
	0x79, 0xc9, 0xe9, 0xec, 0x5b, 0xc7, 0x47, 0xce, 0xb7, 0xd7, 0xdb, 0xbd, 0xd2, 0x08, 0x3e, 0x01,
	0xf9, 0x5c, 0xbc, 0xe2, 0x83, 0xf0, 0x86, 0xaf, 0x80, 0x84, 0x66, 0x76, 0xd7, 0xf6, 0x5d, 0x6c,
	0x2b, 0x08, 0xc4, 0x1b, 0xeb, 0x66, 0x66, 0x77, 0x67, 0xe6, 0x37, 0xbf, 0x99, 0x5d, 0xc3, 0x5a,
	0x5f, 0x88, 0xf3, 0x47, 0xf8, 0x73, 0x90, 0x66, 0x42, 0x09, 0xb6, 0x92, 0xf6, 0x0f, 0x50, 0x74,
	0x7f, 0xab, 0x00, 0x9c, 0xaa, 0x40, 0x45, 0xf2, 0x2b, 0x21, 0xce, 0xd9, 0x1d, 0x68, 0x2b, 0xa1,
	0x82, 0xd8, 0x4f, 0xf2, 0xb1, 0x53, 0xd9, 0xad, 0xec, 0x77, 0xbd, 0x16, 0x29, 0x5e, 0xe5, 0x63,
	0x6d, 0x0c, 0x83, 0x0b, 0x32, 0x56, 0xad, 0x31, 0x0c, 0x2e, 0xd0, 0xe8, 0xc0, 0x4a, 0x16, 0x24,
	0xe7, 0x51, 0x72, 0xe6, 0xd4, 0xc8, 0x64, 0x45, 0xf6, 0x10, 0x9a, 0x4a, 0xa4, 0xfe, 0x93, 0x43,
	0xa7, 0xbe, 0x5b, 0xdb, 0xef, 0x1c, 0xb1, 0x03, 0xe3, 0xfc, 0xe0, 0xb5, 0x48, 0xdf, 0x48, 0x9e,
	0x3d, 0x39, 0xf4, 0x1a, 0x4a, 0xa4, 0x4f, 0x0e, 0xd9, 0x07, 0xd0, 0x1d, 0x66, 0xfc, 0x6d, 0xce,
	0x93, 0x81, 0xf6, 0xd2, 0xa0, 0xa3, 0x56, 0x27, 0x4a, 0xf4, 0x74, 0x0b, 0x5a, 0xb9, 0xe4, 0x19,
	0xd9, 0x9b, 0xda, 0x15, 0xca, 0xaf, 0xf2, 0xb1, 0xfb, 0x29, 0x74, 0xa7, 0xc9, 0x78, 0x32, 0x65,
	0x0f, 0xa0, 0x1e, 0x25, 0x43, 0x41, 0xa9, 0x74, 0x8e, 0x36, 0x26, 0x9e, 0x67, 0x56, 0xd1, 0x02,
	0xf7, 0x7b, 0x68, 0x4f, 0xa2, 0x61, 0x3b, 0x40, 0x27, 0xfa, 0x51, 0x68, 0x30, 0x68, 0xa2, 0x78,
	0x1c, 0x16, 0xe1, 0xa9, 0x5e, 0x85, 0x47, 0xc7, 0x15, 0x8c, 0x39, 0x61, 0xd0, 0xf6, 0x28, 0xd0,
	0x57, 0xc1, 0x98, 0xbb, 0x6f, 0x61, 0x1d, 0xbd, 0x3d, 0x0b, 0x14, 0x97, 0x2f, 0x23, 0xa9, 0x3c,
	0xfe, 0x96, 0xdd, 0x87, 0x9e, 0x1c, 0x89, 0x1f, 0xfd, 0x98, 0x07, 0x59, 0x32, 0x41, 0xbc, 0xe5,
	0xad, 0xa2, 0xf6, 0x25, 0x2a, 0x2d, 0xea, 0x7c, 0x9c, 0xc6, 0x1c, 0xc3, 0xb1, 0x3e, 0x49, 0x71,
	0x1c, 0xb2, 0xdb, 0xd0, 0x4a, 0xe3, 0x40, 0x0d, 0x45, 0x36, 0x76, 0x40, 0xbb, 0xb4, 0xb2, 0xfb,
	0x79, 0xd9, 0xa5, 0x4c, 0xd9, 0x87, 0x50, 0x0f, 0x03, 0x15, 0x38, 0x95, 0x52, 0x25, 0x26, 0x0b,
	0x3d, 0xb2, 0xbb, 0x3f, 0x41, 0x7b, 0xa2, 0x62, 0x3d, 0xa8, 0x4e, 0x90, 0xa8, 0x46, 0x21, 0x63,
	0x50, 0xa7, 0x1c, 0xab, 0xe4, 0x90, 0xbe, 0xb1, 0x28, 0x32, 0xef, 0xfb, 0x83, 0x40, 0x71, 0x5b,
	0x7f, 0x99, 0xf7, 0x71, 0x3f, 0x2e, 0x97, 0x22, 0x53, 0x4e, 0x9d, 0xd4, 0xf4, 0x8d, 0x49, 0x4d,
	0xb3, 0xd6, 0x45, 0x6e, 0xc5, 0x26, 0x63, 0xf7, 0xb2, 0x0a, 0xab, 0xe8, 0xfd, 0x54, 0x1f, 0x70,
	0xbd, 0x00, 0x76, 0x60, 0x05, 0x9d, 0x23, 0x48, 0xda, 0x7f, 0x13, 0x45, 0x53, 0xb3, 0x09, 0x7e,
	0xf5, 0x12, 0x7e, 0x77, 0x01, 0x06, 0x19, 0x0f, 0x14, 0x0f, 0xfd, 0x40, 0x51, 0x20, 0x6d, 0xaf,
	0x6d, 0x34, 0x4f, 0x15, 0xdb, 0x82, 0x66, 0xdf, 0x57, 0x17, 0x29, 0x37, 0x44, 0x6b, 0xf4, 0x5f,
	0x5f, 0xa4, 0x9c, 0x6d, 0x42, 0x23, 0x8e, 0xc6, 0x91, 0x72, 0x56, 0xb4, 0x96, 0x04, 0xb6, 0x0d,
	0x4d, 0x31, 0x1c, 0x4a, 0xae, 0x9c, 0x96, 0x0e, 0x40, 0x4b, 0x6c, 0x0f, 0xea, 0x88, 0xb1, 0xd3,
	0x26, 0xcc, 0xbb, 0x05, 0xcc, 0x3d, 0x32, 0x2d, 0x2d, 0x63, 0x1f, 0x36, 0x66, 0xc1, 0xb0, 0xe4,
	0xf9, 0xac, 0x88, 0x91, 0x61, 0xf8, 0x56, 0xe1, 0x74, 0x6b, 0xf4, 0x8a, 0x70, 0xae, 0x43, 0x2d,
	0x0a, 0xa5, 0x53, 0xdd, 0xad, 0xed, 0x77, 0x3d, 0xfc, 0x74, 0xbf, 0x9b, 0xe3, 0x43, 0xa6, 0x98,
	0x27, 0xb1, 0x9b, 0x0e, 0xaf, 0x79, 0x5a, 0x60, 0x0f, 0x0d, 0x87, 0xaa, 0x94, 0xcf, 0x02, 0x8f,
	0x9a, 0x46, 0x5f, 0x40, 0xfb, 0x99, 0x18, 0x8f, 0x45, 0x82, 0xa7, 0xf5, 0xa0, 0x2a, 0xce, 0x0d,
	0xc5, 0xab, 0xe2, 0x1c, 0xc3, 0x18, 0xcb, 0x33, 0x53, 0x44, 0xfc, 0x34, 0x75, 0xae, 0xd9, 0x3a,
	0xbb, 0x2f, 0xa0, 0x83, 0x87, 0x2e, 0x0f, 0x67, 0xaf, 0x10, 0x4e, 0x19, 0x5e, 0x0a, 0xe3, 0x8f,
	0x3a, 0xd4, 0x69, 0xbc, 0x95, 0x89, 0x84, 0x27, 0x46, 0x2a, 0xb6, 0x4c, 0xd2, 0xc2, 0x62, 0x2a,
	0xdd, 0x83, 0x8e, 0x25, 0xf9, 0x94, 0x4c, 0x6d, 0xc3, 0xf3, 0xe3, 0x10, 0x67, 0xa0, 0x54, 0x22,
	0x0b, 0xce, 0xb8, 0xe1, 0xb4, 0x15, 0xd1, 0xd1, 0xbb, 0x28, 0xe4, 0x82, 0x78, 0xd4, 0xf6, 0xb4,
	0x80, 0xda, 0x20, 0x0f, 0x23, 0x61, 0x79, 0x44, 0x02, 0x12, 0x16, 0x13, 0xf0, 0x87, 0x51, 0xcc,
	0x0d, 0x95, 0x5a, 0xa8, 0x78, 0x11, 0xc5, 0x9c, 0x5c, 0xe4, 0xfd, 0x1f, 0xf8, 0x40, 0x39, 0x6d,
	0x3a, 0xca, 0x8a, 0x68, 0x19, 0x88, 0x44, 0xf1, 0x44, 0x19, 0x0a, 0x59, 0x11, 0x0f, 0x8c, 0xa4,
	0x9f, 0xe6, 0x71, 0x24, 0x47, 0x4e, 0x67, 0xb7, 0xb2, 0xdf, 0xf0, 0x5a, 0x91, 0x3c, 0x21, 0x19,
	0x7b, 0x69, 0x14, 0x29, 0xe9, 0xac, 0xea, 0xee, 0xc4, 0xef, 0x62, 0xcb, 0x74, 0x4b, 0x2d, 0x33,
	0x33, 0x1c, 0x7b, 0x85, 0xe1, 0xb8, 0x0d, 0xcd, 0x20, 0x57, 0x23, 0x91, 0x39, 0x6b, 0xe4, 0xdf,
	0x48, 0xa5, 0x1e, 0x5b, 0x2f, 0xf7, 0xd8, 0x5d, 0x80, 0x3c, 0x0d, 0xad, 0xf9, 0xa6, 0x36, 0x1b,
	0xcd, 0x53, 0x35, 0xed, 0x35, 0x36, 0xbf, 0xd7, 0x36, 0x0a, 0xbd, 0xf6, 0x7f, 0xe8, 0x8c, 0x02,
	0xe9, 0x0f, 0x44, 0x1c, 0x23, 0x44, 0x9b, 0x44, 0x36, 0x18, 0x05, 0xf2, 0x99, 0xd6, 0xb0, 0x23,
	0x44, 0x49, 0x1b, 0xb7, 0xa8, 0x63, 0x9c, 0xe2, 0x0c, 0xd4, 0xb6, 0x48, 0x24, 0xd2, 0xb3, 0x0b,
	0x0b, 0xdd, 0xb9, 0x5d, 0xec, 0x4e, 0x84, 0x6f, 0x18, 0x07, 0x67, 0xce, 0x8e, 0x86, 0x0f, 0xbf,
	0xdd, 0xa7, 0xd0, 0xc0, 0x8b, 0xe4, 0x7a, 0x73, 0x6b, 0x13, 0x1a, 0xe9, 0x48, 0x24, 0xf6, 0xc6,
	0xd0, 0x82, 0xfb, 0x67, 0x05, 0xd6, 0x4a, 0xf1, 0x2c, 0xbf, 0x95, 0x16, 0xde, 0x10, 0x3b, 0xb0,
	0x42, 0x6c, 0x9a, 0x92, 0x19, 0xc5, 0xe3, 0x90, 0xfd, 0x0f, 0xda, 0x93, 0x6b, 0xd5, 0x52, 0x79,
	0xa2, 0x60, 0x0f, 0x61, 0x7d, 0x20, 0xf0, 0x08, 0xf4, 0xed, 0x67, 0x81, 0x8a, 0x84, 0xe1, 0xf4,
	0xda, 0x54, 0xef, 0xa1, 0xba, 0x78, 0x29, 0x36, 0x4b, 0x97, 0xe2, 0x36, 0x34, 0xa5, 0x0a, 0x54,
	0x2e, 0x0d, 0xc7, 0x8d, 0x54, 0x22, 0x45, 0xab, 0x44, 0x0a, 0xf7, 0xf7, 0x0a, 0x00, 0x35, 0x30,
	0x1f, 0x88, 0x2c, 0xbc, 0x02, 0xe4, 0x4c, 0x52, 0xd5, 0x42, 0x52, 0x33, 0x18, 0xd5, 0x16, 0x63,
	0x54, 0xbe, 0x05, 0x0a, 0x19, 0x34, 0x4a, 0x19, 0x14, 0x23, 0x6d, 0x96, 0xe9, 0x6b, 0xbb, 0x95,
	0x0a, 0xbb, 0xa2, 0xd9, 0x81, 0x0a, 0xbc, 0xf5, 0x71, 0x36, 0xa5, 0x38, 0x0d, 0x5a, 0x44, 0xb5,
	0xe9, 0x6c, 0x3a, 0x09, 0xce, 0xb8, 0x47, 0x26, 0xd7, 0x83, 0x9b, 0xd3, 0x44, 0x97, 0x4f, 0xba,
	0x07, 0x85, 0x49, 0xb7, 0x51, 0x9c, 0x74, 0xb4, 0xdf, 0xcc, 0xbb, 0xc7, 0x50, 0x3f, 0x31, 0x53,
	0x47, 0xf7, 0x4e, 0x65, 0x7e, 0xef, 0x54, 0x67, 0x7b, 0xc7, 0xf5, 0xf4, 0xb4, 0x3d, 0x4e, 0x86,
	0xe2, 0x7a, 0xe3, 0x7a, 0xcf, 0x3c, 0xae, 0x6a, 0xa5, 0xec, 0x66, 0x9e, 0x55, 0x11, 0x74, 0xa7,
	0xd1, 0x3d, 0x7f, 0xaf, 0xd8, 0x63, 0xe8, 0x10, 0x5c, 0x19, 0x69, 0xae, 0xbc, 0xcb, 0x66, 0x52,
	0x81, 0xfe, 0xb4, 0xfe, 0x2e, 0xd4, 0xb1, 0x8e, 0xe4, 0xbc, 0x73, 0xd4, 0x9b, 0x2c, 0xa7, 0x36,
	0xf3, 0xc8, 0xe6, 0x7e, 0x39, 0x0b, 0xa4, 0x4d, 0xe2, 0xa3, 0xc2, 0xfb, 0x6f, 0x7b, 0x8e, 0x9f,
	0xe7, 0xef, 0x95, 0x89, 0xf5, 0xd7, 0x0a, 0x30, 0xdd, 0x73, 0xc4, 0x6f, 0xfe, 0xdf, 0x70, 0x6f,
	0x13, 0x1a, 0xd1, 0x78, 0x7a, 0x63, 0x68, 0xe1, 0x9f, 0x90, 0xce, 0xbd, 0xac, 0xc0, 0xad, 0xab,
	0x79, 0xd8, 0x77, 0xc3, 0x37, 0xf3, 0x92, 0x34, 0xf8, 0xdc, 0x29, 0xcd, 0xc2, 0xd9, 0x25, 0xde,
	0x3c, 0x6c, 0xf6, 0x34, 0xd1, 0x4c, 0x5d, 0xca, 0xfc, 0xc6, 0x5f, 0xf7, 0x97, 0x0a, 0x6c, 0x5d,
	0xdd, 0x89, 0x54, 0xf8, 0x57, 0x23, 0xb9, 0x6f, 0x66, 0xee, 0x02, 0x8a, 0x68, 0xa3, 0xdb, 0x5f,
	0x88, 0xcc, 0xc2, 0xa6, 0x7b, 0x54, 0x68, 0xba, 0xa5, 0x71, 0xe9, 0xe6, 0xfb, 0x76, 0x9e, 0x0f,
	0xcb, 0xc7, 0xa3, 0x02, 0x1f, 0xef, 0x2d, 0x39, 0x6d, 0xca, 0xcb, 0x9f, 0x75, 0x5f, 0x9e, 0x5e,
	0x24, 0x03, 0x2c, 0xe0, 0x5d, 0x00, 0xc5, 0xc7, 0x71, 0x8a, 0x6c, 0x92, 0xf4, 0x90, 0xef, 0x7a,
	0x6d, 0xad, 0x39, 0x0e, 0x25, 0xdb, 0x87, 0x75, 0x29, 0xf2, 0x6c, 0xc0, 0xfd, 0xf2, 0x9d, 0xd0,
	0xd3, 0xfa, 0xd7, 0x96, 0x79, 0xf7, 0xa1, 0x17, 0x49, 0x5f, 0x5e, 0x24, 0x03, 0x3f, 0xcd, 0xfb,
	0x71, 0x34, 0x30, 0xb4, 0x5d, 0x8d, 0x24, 0xfa, 0x3a, 0x21, 0xdd, 0xd1, 0x65, 0xd5, 0xb8, 0xe7,
	0xd9, 0xbb, 0x68, 0xc0, 0xd9, 0xc7, 0xd0, 0xb2, 0x6f, 0x32, 0x56, 0x6c, 0xf9, 0xdb, 0x9b, 0x05,
	0xd1, 0xc0, 0xea, 0xde, 0xb0, 0x5b, 0x10, 0x83, 0xe5, 0x5b, 0x0c, 0x4a, 0xee, 0x0d, 0x76, 0xa8,
	0xff, 0x7f, 0x9c, 0x2a, 0x91, 0xf1, 0xf2, 0x9e, 0xe9, 0xbf, 0x96, 0xc9, 0xdb, 0x92, 0x9c, 0xd0,
	0x85, 0xf1, 0x86, 0x1e, 0x0e, 0x7f, 0x6b, 0xcb, 0xd7, 0x1c, 0x51, 0xbf, 0xd6, 0x96, 0x7e, 0x93,
	0xfe, 0x3e, 0x7f, 0xf2, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x57, 0xeb, 0x31, 0x51, 0x0f,
	0x00, 0x00,
}
