// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: book/book.proto

package pb_book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BookService service

type BookService interface {
	BookList(ctx context.Context, in *Book, opts ...client.CallOption) (*BookListRsp, error)
	BookInfo(ctx context.Context, in *Book, opts ...client.CallOption) (*BookInfoRsp, error)
	BookStore(ctx context.Context, in *Book, opts ...client.CallOption) (*CommonRsp, error)
	BookUpdate(ctx context.Context, in *Book, opts ...client.CallOption) (*CommonRsp, error)
	BookDelete(ctx context.Context, in *Book, opts ...client.CallOption) (*CommonRsp, error)
}

type bookService struct {
	c    client.Client
	name string
}

func NewBookService(name string, c client.Client) BookService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pb.book"
	}
	return &bookService{
		c:    c,
		name: name,
	}
}

func (c *bookService) BookList(ctx context.Context, in *Book, opts ...client.CallOption) (*BookListRsp, error) {
	req := c.c.NewRequest(c.name, "BookService.BookList", in)
	out := new(BookListRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) BookInfo(ctx context.Context, in *Book, opts ...client.CallOption) (*BookInfoRsp, error) {
	req := c.c.NewRequest(c.name, "BookService.BookInfo", in)
	out := new(BookInfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) BookStore(ctx context.Context, in *Book, opts ...client.CallOption) (*CommonRsp, error) {
	req := c.c.NewRequest(c.name, "BookService.BookStore", in)
	out := new(CommonRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) BookUpdate(ctx context.Context, in *Book, opts ...client.CallOption) (*CommonRsp, error) {
	req := c.c.NewRequest(c.name, "BookService.BookUpdate", in)
	out := new(CommonRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) BookDelete(ctx context.Context, in *Book, opts ...client.CallOption) (*CommonRsp, error) {
	req := c.c.NewRequest(c.name, "BookService.BookDelete", in)
	out := new(CommonRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceHandler interface {
	BookList(context.Context, *Book, *BookListRsp) error
	BookInfo(context.Context, *Book, *BookInfoRsp) error
	BookStore(context.Context, *Book, *CommonRsp) error
	BookUpdate(context.Context, *Book, *CommonRsp) error
	BookDelete(context.Context, *Book, *CommonRsp) error
}

func RegisterBookServiceHandler(s server.Server, hdlr BookServiceHandler, opts ...server.HandlerOption) error {
	type bookService interface {
		BookList(ctx context.Context, in *Book, out *BookListRsp) error
		BookInfo(ctx context.Context, in *Book, out *BookInfoRsp) error
		BookStore(ctx context.Context, in *Book, out *CommonRsp) error
		BookUpdate(ctx context.Context, in *Book, out *CommonRsp) error
		BookDelete(ctx context.Context, in *Book, out *CommonRsp) error
	}
	type BookService struct {
		bookService
	}
	h := &bookServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&BookService{h}, opts...))
}

type bookServiceHandler struct {
	BookServiceHandler
}

func (h *bookServiceHandler) BookList(ctx context.Context, in *Book, out *BookListRsp) error {
	return h.BookServiceHandler.BookList(ctx, in, out)
}

func (h *bookServiceHandler) BookInfo(ctx context.Context, in *Book, out *BookInfoRsp) error {
	return h.BookServiceHandler.BookInfo(ctx, in, out)
}

func (h *bookServiceHandler) BookStore(ctx context.Context, in *Book, out *CommonRsp) error {
	return h.BookServiceHandler.BookStore(ctx, in, out)
}

func (h *bookServiceHandler) BookUpdate(ctx context.Context, in *Book, out *CommonRsp) error {
	return h.BookServiceHandler.BookUpdate(ctx, in, out)
}

func (h *bookServiceHandler) BookDelete(ctx context.Context, in *Book, out *CommonRsp) error {
	return h.BookServiceHandler.BookDelete(ctx, in, out)
}
