apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: model-db-pv-claim
    namespace: default
  hostPath:
    path: /Volumes/backup/k8s/mysql/persistence/data
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem